### ISSUE TITLE
Unable to resolve BaseFableHubOptions when trying to connect

### ISSUE THREAD

**Issue by MargaretKrutikova** [Shmew/Fable.SignalR#11]
## Description

I followed the basic setup in the docs, but when the client attempts to connect to the hub, the api throws the following exception:
```
Microsoft.AspNetCore.SignalR.HubConnectionHandler[1]
      Error when dispatching 'OnConnectedAsync' on hub.
      System.InvalidOperationException: Unable to resolve service for type 'Fable.SignalR.BaseFableHubOptions`2[Api.SignalRHub+SignalRAction,Api.SignalRHub+Response]' while attempting to activate 'Fable.SignalR.BaseFableHub`2[Api.SignalRHub+SignalRAction,Api.SignalRHub+Response]'.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
         at lambda_method44(Closure , IServiceProvider , Object[] )
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubActivator`1.Create()
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
         at Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher`1.OnConnectedAsync(HubConnectionContext connection)
         at Microsoft.AspNetCore.SignalR.HubConnectionHandler`1.RunHubAsync(HubConnectionContext connection)
```
Appreciate any help!

**Comment by Shmew** [comment]
Hi @MargaretKrutikova, I tried to reproduce this error without any luck. Could you please provide some additional details or a reproduction, and what version you're on?

**Comment by MargaretKrutikova** [comment]
The version of the package I am using is `0.11.0`.
One thing I noticed is that the demo project in this repo references `netcoreapp3.1`, while I am targeting `net5.0`, which is newer, could that be causing the problem?

**Comment by Shmew** [comment]
Doesn't appear to be the case, I updated the demo to run on net5.0 and it all worked fine. 😞

**Comment by MargaretKrutikova** [comment]
I think it works now, though takes like a minute to connect the first time. I was missing (of course ... 🤦 ) a step from the setup, didn't pass my config into `AddSignalR`:
```
let myConfig serviceCollection =
    serviceCollection.AddSignalR(mySignalRConfig)
```
Thanks for looking into this! Will close this for now 🙂

**Comment by Shmew** [comment]
It shouldn't take very long to connect if the server is already running. One thing to keep in mind with the default automatic reconnect is that it backs off reconnection attempts with increasing duration before the next one until it gives up. You can also modify that behavior by creating your own [policy](https://shmew.github.io/Fable.SignalR/#/signalr-client/api#retrypolicy).
