### ISSUE TITLE
Authorization Documentation does not match codebase

### ISSUE THREAD

**Issue by rickfleming** [Shmew/Fable.SignalR#12]
## Description
In the Authorization documentation here:

https://shmew.github.io/Fable.SignalR/#/authorization

It says for ASP.NET Core/Giraffe you can use the SignalR.ConfigBuilder, however the example code is invalid.  The "Build" method at the end of the DSL chain is internal in the ConfigBuilder type, so ConfigBuilder doesn't seem to be usable.

## Steps to reproduce
Just use the example from the documentation in a project that isn't considered internal to the libraries.

## Expected behavior
Build to be public so it can be called and ConfigBuilder used.

**Comment by Shmew** [comment]
Whoops, sorry about that! I've released a new version which should resolve the issue.
