### ISSUE TITLE
SignalR & SAFE Stack (Saturn/Giraffe) & Net5.0

### ISSUE THREAD

**Issue by KingKnecht** [Shmew/Fable.SignalR#13]
## Description
I get following compile error:
`error NU1202: Package Microsoft.AspNetCore.Authentication.JwtBearer 5.0.1 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1). Package Microsoft.AspNetCore.Authentication.JwtBearer 5.0.1 supports: net5.0 (.NETCoreApp,Version=v5.0)`
## Steps to reproduce

1. Install the SAFE-Stack template 
2. Create new project from the template
3. Follow the installation instructions for Fable.SignalR
4. Compile with `dotnet fake build -t run`

Produces the shown error.
## Expected behavior
I'm not sure. I'm pretty new to all this Fable/F#/netcore stuff. As far as I understand the SAFE template uses netcoreapp3.1 and it looks like Fable.SignalR adds a dependency (via Microsoft.AspNetCore.Authentication.JwtBearer) to net5.0. 
So, there is no way to use Fable.SignalR with netcoreapp3.1?

Or could I try to install an older version? If so, which one?

I would be grateful for any advice. If it's not a Fable.SignalR problem, please let me know. It's very confusing for a newbie to see who is responsible for which package etc.

**Comment by KingKnecht** [comment]
Addendum:
I'm trying to build a collaborative Todos-List. That is, when one client adds a Todo to the list, all other clients should be informed about the change of the list and update their model accordingly.. 
Maybe it's just a bad idea to add SignalR for this? I'm lost 🤣

**Comment by Shmew** [comment]
Hi @KingKnecht,

Hmm, everything works locally in the project with both 3.1 and 5.0. I'm starting to wonder if it's specifically how Paket is creating the nuspec that's causing issues. For a quick fix you can pin the version to 0.10.1 and it should work as expected.

> I'm trying to build a collaborative Todos-List. That is, when one client adds a Todo to the list, all other clients should be informed about the change of the list and update their model accordingly.
Maybe it's just a bad idea to add SignalR for this? I'm lost 🤣

I'd say any time you want real-time updates SignalR is a good solution.

**Comment by KingKnecht** [comment]
Got this compiling with version 0.10.1. Thx.

**Comment by Shmew** [comment]
Hey @KingKnecht, I finally got around to figuring out what was up with my packaging. You should be able to unpin your version now once 0.11.2 validates on nuget.
