### ISSUE TITLE
Q: IDisposable

### ISSUE THREAD

**Issue by KingKnecht** [Shmew/Fable.SignalR#14]
From the docs:
```
type Model =
    { Count: int
      Text: string
      Hub: Elmish.Hub<Action,Response> option }

    // This only works if you're using Feliz.UseElmish or Feliz.ElmishComponents!
    //
    // If you're using the traditional elmish model you will need to clean this up yourself.
    interface System.IDisposable with
        member this.Dispose () =
            this.Hub |> Option.iter (fun hub -> hub.Dispose())
```
What does mean? When do I have to dispose the hub? Every time I create a new model? Or only once at the end of my application?

**Comment by Shmew** [comment]
This feature is for when a connection isn't needed all the time, or if you want to use multiple hubs in your application. 

So for example if you only need a connection when a user is on a specific page you can dispose the connection when they navigate to a different part of the site and then re-establish when they go back to it.
