### ISSUE TITLE
Elmish example for server streaming

### ISSUE THREAD

**Issue by SlavkaOnline** [Shmew/Fable.SignalR#17]
Could you give the full demo of using SignalR with Elmish?
I can't understand the example (https://shmew.github.io/Fable.SignalR/#/signalr-client/streaming-server), what does mean 'Subscription' there 
```
 | StartServerStream ->
        let subscriber dispatch =
            { next = SignalRStreamMsg >> dispatch
              complete = fun () -> StreamStatus.Finished |> StreamStatus |> dispatch
              error = StreamStatus.Error >> StreamStatus >> dispatch }

        { model with StreamStatus = StreamStatus.Streaming }
        , Cmd.SignalR.streamFrom model.Hub StreamFrom.Action.GenInts **Subscription** subscriber
```
How to get this object?

**Comment by Shmew** [comment]
Oh sorry, it looks like I need to fix the documentation. I accidentally omitted the DU case for that. You can see how it's done in the [unit tests](https://github.com/Shmew/Fable.SignalR/blob/master/tests/Fable.SignalR.Tests/Components.fs#L180-L300).

```fsharp
type Msg =
    ...
    | Subscription of System.IDisposable

let update msg model =
    match msg with
    | Subscription sub ->
       { model with StreamSubscription = Some sub }, Cmd.none
    ...
```
