### ISSUE TITLE
Split into bindings and a library

### ISSUE THREAD

**Issue by Prunkles** [Shmew/Fable.SignalR#18]
I think that it would be nice if the library was split into two parts:
1. Fable bindings. Literally a 1-to-1 copy of the corresponding JS library (`@microsoft/signalr`), without any additional idiomatic F# features, but with types.
  And according to the de facto standard, it should be called as `Fable.Import.SignalR`.
2. The library as it is now. Action/Response feature, client-server interaction, and so on.
  I'm not sure if keeping the `Fable.SignalR` name in this case is a good idea, but I have no suggestions yet.

My point is to provide also just Fable bindings if someone needs it, but doesn't need the whole set of library functions.

**Comment by Shmew** [comment]
This could be done, but it makes things quite unsafe. I don't really have the time (or desire to be honest) to do this, but I'd be willing to accept a PR if you or someone else wants to take up that task.
