### ISSUE TITLE
Latest Fable.SignalR.AspNetCore requires Fable.Remoting.MsgPack below 1.7

### ISSUE THREAD

**Issue by theimowski** [Shmew/Fable.SignalR#20]
Given following dependencies:

```
source https://api.nuget.org/v3/index.json
framework: net5.0
storage: none

nuget Fable.Remoting.Giraffe
nuget Saturn
nuget Expecto

nuget Fable.FontAwesome.Free
nuget Fable.Mocha
nuget Fable.Remoting.Client
nuget Fable.SignalR.Saturn
nuget Fable.SignalR.Feliz
nuget Feliz.Bulma
nuget Fulma

nuget Fake.Core.ReleaseNotes
nuget Fake.Core.Target
nuget Fake.DotNet.Cli
nuget Farmer
```

when I'm trying to do paket update, it fails to find a valid resolution due to:

```
Paket may still find a valid resolution, but this might take a while.
  Conflict detected:
   - Fable.SignalR.AspNetCore 0.11.2 requested package Fable.Remoting.MsgPack: >= 1.6.2 < 1.7
   - Fable.Remoting.Client 7.6.0 requested package Fable.Remoting.MsgPack: >= 1.8
   - Fable.SignalR 0.11.2 requested package Fable.Remoting.MsgPack: >= 1.6.2 < 2.0
```

I think this is due to the project having a `~>` pinned dependency on locked version of Fable.Remoting.MsgPack, hence in nuspec it ends up as `< 1.7`
If there's no breaking change in that dependency, then possibly loosening that restriction could help fix the issue.

As a workaround I could try defining separate paket groups for Client and Server dependencies, but I'd rather have a single group unless there's a good reason not to.

**Comment by Zaid-Ajaj** [comment]
for 
```
Fable.SignalR.AspNetCore 0.11.2 requested package Fable.Remoting.MsgPack: >= 1.6.2 < 1.7
```
You can safely change the requirements to `>= 1.6.2 < 2.0.0` for remoting packages I usually increment the minor version instead of the patch

**Comment by Shmew** [comment]
Whoops, looks like this was caused by all the finagling I had to do to enable paket to play nice with multi targeting. I'm pushing version `0.11.3` now, which should properly pin to the major version for dependencies.
