### ISSUE TITLE
Question: does client package assume the use of server package?

### ISSUE THREAD

**Issue by kentcb** [Shmew/Fable.SignalR#30]
Hello,

Thanks for this library. First time user here, so apologies if I'm asking something dumb.

I was trying to determine from the docs whether the client library _requires_ the use of the server library, or whether it could integrate with an existing SignalR backend.

Context: I already have a SignalR stream API that is using a channel rather than async enumerable. It doesn't seem as straightforward as I'd hoped to convert from a channel-based implementation to one based on async enumerable, and if I was to convert my backend, Fable.SignalR seems to only support the latter. So that got me wondering whether I could just integrate directly.

**Comment by Shmew** [comment]
Hi @kentcb,

The library does indeed assume a matching backend implementation, as it assumes a very specific implementation of the hub, as well as when using MsgPack it requires a [custom implementation](https://github.com/Shmew/Fable.SignalR/blob/master/src/Fable.SignalR.Shared/MsgPack.fs) of the `IHubProtocol`.

I haven't had to deal with this myself, but channels should be able to be used with [this method](https://docs.microsoft.com/en-us/dotnet/api/system.threading.channels.channelreader-1.readallasync?view=net-5.0).

**Comment by kentcb** [comment]
Thanks for confirming
