### ISSUE TITLE
docs refer to "optional dependencies listed above" but I don't see them listed

### ISSUE THREAD

**Issue by simonmcconnell** [Shmew/Fable.SignalR#4]
In the Femto section on the [installation](https://shmew.github.io/Fable.SignalR/#/installation) page in the docs it says "Do note that this will not install the optional dependencies listed above (the babel plugin and prettier)."  

I don't see these listed above.  Am I missing something?

**Comment by Shmew** [comment]
Oh whoops, that's left over from when I copied my docs setup from a different project. I'll go fix that, thanks!
