### ISSUE TITLE
Getting that the Namespace Http is missing, when I use the Emlish Package

### ISSUE THREAD

**Issue by DieselMeister** [Shmew/Fable.SignalR#5]
" ./.fable/Fable.SignalR.0.4.0/HubConnection.fs   (306,50) error FSHARP: The namespace or module 'Http' is not defined. Maybe you want one of the following: " 

So maybe some package is missing? 

paket dependencies forthe client:

group Client
    FSharp.Core
    Fable.Core
    Fable.Elmish.Debugger
    Fable.Elmish.React
    Fable.Elmish.HMR
    Thoth.Fetch
    Fulma
    Fable.FontAwesome.Free
    Fable.SignalR.Elmish

**Comment by Shmew** [comment]
Ah, yes you need the base `Fable.SignalR` package. `Fable.SignalR.Elmish` is an extension library.

**Comment by DieselMeister** [comment]
Hi. Sorry same issue.

![image](https://user-images.githubusercontent.com/13096516/88179627-7f06c980-cc2c-11ea-9990-17641aca6dad.png)

group Client
    FSharp.Core
    Fable.Core
    Fable.Elmish.Debugger
    Fable.Elmish.React
    Fable.Elmish.HMR
    Thoth.Fetch
    Fulma
    Fable.FontAwesome.Free
    Fable.SignalR
    Fable.SignalR.Elmish

**Comment by DieselMeister** [comment]
Sorry, now it works. Seems I used an "too" old version of the fable compiler. Also removed Fulma and Thoth. Sorry for the inconvenient. Thank you for you awesome work.

**Comment by Shmew** [comment]
No worries, glad you found the fix!
